# Generated by Django 5.0.1 on 2025-12-30 11:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("routes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("reversed", "Reversed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(100)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("XAF", "Central African Franc"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                        ],
                        default="XAF",
                        max_length=3,
                    ),
                ),
                (
                    "service_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="amount + service_fee",
                        max_digits=15,
                    ),
                ),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_phone", models.CharField(db_index=True, max_length=20)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("provider", models.CharField(default="awdpay", max_length=50)),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        help_text="Internal reference used with provider.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID returned by provider (AwdPay).",
                        max_length=128,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransferAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("provider_init", "Provider Initiated"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("webhook_received", "Webhook Received"),
                            ("webhook_processed", "Webhook Processed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="transfers.transfer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransferLimitSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_sent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("transfer_count", models.IntegerField(default=0)),
                ("daily_date", models.DateField()),
                (
                    "daily_sent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("daily_count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "funding_method_type",
                    models.CharField(
                        choices=[
                            ("mobile_money", "Mobile Money"),
                            ("card", "Card"),
                            ("bank", "Bank"),
                        ],
                        help_text="How sender pays: mobile money, card, etc.",
                        max_length=20,
                    ),
                ),
                (
                    "funding_mobile_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mtn_cm", "MTN Cameroon"),
                            ("orange_cm", "Orange Money Cameroon"),
                            ("wave_sn", "Wave Senegal"),
                            ("mtn_ci", "MTN Côte d’Ivoire"),
                            ("orange_ci", "Orange Money Côte d’Ivoire"),
                        ],
                        max_length=50,
                    ),
                ),
                ("funding_card_scheme", models.CharField(blank=True, max_length=20)),
                (
                    "payout_method_type",
                    models.CharField(
                        choices=[
                            ("mobile_money", "Mobile Money"),
                            ("card", "Card"),
                            ("bank", "Bank"),
                        ],
                        help_text="How recipient receives: mobile money, bank, etc.",
                        max_length=20,
                    ),
                ),
                (
                    "payout_mobile_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mtn_cm", "MTN Cameroon"),
                            ("orange_cm", "Orange Money Cameroon"),
                            ("wave_sn", "Wave Senegal"),
                            ("mtn_ci", "MTN Côte d’Ivoire"),
                            ("orange_ci", "Orange Money Côte d’Ivoire"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "corridor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source → destination corridor used for this transfer.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="routes.corridor",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_limits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer Limit Snapshot",
                "verbose_name_plural": "Transfer Limit Snapshots",
            },
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["user", "-created_at"], name="transfers_t_user_id_a200ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["status", "-created_at"], name="transfers_t_status_848455_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["reference"], name="transfers_t_referen_fabfdc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["provider_id"], name="transfers_t_provide_ddc123_idx"
            ),
        ),
    ]
