# Generated by Django 5.0.1 on 2026-01-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transfers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferlimitsnapshot",
            name="funding_mobile_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mtn_cm", "MTN Mobile Money (Cameroon)"),
                    ("orange_cm", "Orange Money (Cameroon)"),
                    ("mtn_ci", "MTN Mobile Money (Côte d'Ivoire)"),
                    ("orange_ci", "Orange Money (Côte d'Ivoire)"),
                    ("moov_ci", "Moov Money (Côte d'Ivoire)"),
                    ("wave_ci", "Wave (Côte d'Ivoire)"),
                    ("orange_sn", "Orange Money (Senegal)"),
                    ("free_sn", "Free Money (Senegal)"),
                    ("wave_sn", "Wave (Senegal)"),
                    ("orange_ml", "Orange Money (Mali)"),
                    ("moov_ml", "Moov Money (Mali)"),
                    ("orange_bf", "Orange Money (Burkina Faso)"),
                    ("moov_bf", "Moov Money (Burkina Faso)"),
                    ("togocom_tg", "Togocom Money (Togo)"),
                    ("moov_tg", "Moov Money (Togo)"),
                    ("mtn_bj", "MTN Mobile Money (Benin)"),
                    ("moov_bj", "Moov Money (Benin)"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="transferlimitsnapshot",
            name="payout_mobile_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mtn_cm", "MTN Mobile Money (Cameroon)"),
                    ("orange_cm", "Orange Money (Cameroon)"),
                    ("mtn_ci", "MTN Mobile Money (Côte d'Ivoire)"),
                    ("orange_ci", "Orange Money (Côte d'Ivoire)"),
                    ("moov_ci", "Moov Money (Côte d'Ivoire)"),
                    ("wave_ci", "Wave (Côte d'Ivoire)"),
                    ("orange_sn", "Orange Money (Senegal)"),
                    ("free_sn", "Free Money (Senegal)"),
                    ("wave_sn", "Wave (Senegal)"),
                    ("orange_ml", "Orange Money (Mali)"),
                    ("moov_ml", "Moov Money (Mali)"),
                    ("orange_bf", "Orange Money (Burkina Faso)"),
                    ("moov_bf", "Moov Money (Burkina Faso)"),
                    ("togocom_tg", "Togocom Money (Togo)"),
                    ("moov_tg", "Moov Money (Togo)"),
                    ("mtn_bj", "MTN Mobile Money (Benin)"),
                    ("moov_bj", "Moov Money (Benin)"),
                ],
                max_length=50,
            ),
        ),
    ]
