# Generated by Django 5.0.1 on 2026-02-13 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_corridorpayoutmethod_unique_together_and_more'),
        ('transfers', '0002_alter_transferlimitsnapshot_funding_mobile_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='corridor',
            field=models.ForeignKey(blank=True, help_text='Source -> destination corridor used for this transfer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corridor_transfers', to='routes.corridor'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='deposit_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='deposit_gateway',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transfer',
            name='deposit_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='deposit_reference',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='transfer',
            name='deposit_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transfer',
            name='destination_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount the receiver gets in destination currency.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='destination_currency',
            field=models.CharField(blank=True, choices=[('XAF', 'Central African Franc'), ('XOF', 'West African Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], help_text='Currency the receiver gets (e.g. XOF).', max_length=3),
        ),
        migrations.AddField(
            model_name='transfer',
            name='funding_mobile_provider',
            field=models.CharField(blank=True, choices=[('mtn_cm', 'MTN Mobile Money (Cameroon)'), ('orange_cm', 'Orange Money (Cameroon)'), ('mtn_ci', "MTN Mobile Money (Côte d'Ivoire)"), ('orange_ci', "Orange Money (Côte d'Ivoire)"), ('moov_ci', "Moov Money (Côte d'Ivoire)"), ('wave_ci', "Wave (Côte d'Ivoire)"), ('orange_sn', 'Orange Money (Senegal)'), ('free_sn', 'Free Money (Senegal)'), ('wave_sn', 'Wave (Senegal)'), ('orange_ml', 'Orange Money (Mali)'), ('moov_ml', 'Moov Money (Mali)'), ('orange_bf', 'Orange Money (Burkina Faso)'), ('moov_bf', 'Moov Money (Burkina Faso)'), ('togocom_tg', 'Togocom Money (Togo)'), ('moov_tg', 'Moov Money (Togo)'), ('mtn_bj', 'MTN Mobile Money (Benin)'), ('moov_bj', 'Moov Money (Benin)')], help_text="Sender's mobile money provider (e.g. mtn_cm).", max_length=50),
        ),
        migrations.AddField(
            model_name='transfer',
            name='payout_mobile_provider',
            field=models.CharField(blank=True, choices=[('mtn_cm', 'MTN Mobile Money (Cameroon)'), ('orange_cm', 'Orange Money (Cameroon)'), ('mtn_ci', "MTN Mobile Money (Côte d'Ivoire)"), ('orange_ci', "Orange Money (Côte d'Ivoire)"), ('moov_ci', "Moov Money (Côte d'Ivoire)"), ('wave_ci', "Wave (Côte d'Ivoire)"), ('orange_sn', 'Orange Money (Senegal)'), ('free_sn', 'Free Money (Senegal)'), ('wave_sn', 'Wave (Senegal)'), ('orange_ml', 'Orange Money (Mali)'), ('moov_ml', 'Moov Money (Mali)'), ('orange_bf', 'Orange Money (Burkina Faso)'), ('moov_bf', 'Moov Money (Burkina Faso)'), ('togocom_tg', 'Togocom Money (Togo)'), ('moov_tg', 'Moov Money (Togo)'), ('mtn_bj', 'MTN Mobile Money (Benin)'), ('moov_bj', 'Moov Money (Benin)')], help_text="Receiver's mobile money provider (e.g. wave_ci).", max_length=50),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_phone',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transfer',
            name='withdrawal_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='withdrawal_gateway',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transfer',
            name='withdrawal_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='withdrawal_reference',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='transfer',
            name='withdrawal_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='currency',
            field=models.CharField(choices=[('XAF', 'Central African Franc'), ('XOF', 'West African Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='XAF', max_length=3),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deposit_pending', 'Deposit Pending'), ('deposit_confirmed', 'Deposit Confirmed'), ('deposit_failed', 'Deposit Failed'), ('withdrawal_pending', 'Withdrawal Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='transferauditlog',
            name='event',
            field=models.CharField(choices=[('created', 'Created'), ('provider_init', 'Provider Initiated'), ('deposit_initiated', 'Deposit Initiated'), ('deposit_confirmed', 'Deposit Confirmed'), ('deposit_failed', 'Deposit Failed'), ('withdrawal_initiated', 'Withdrawal Initiated'), ('withdrawal_confirmed', 'Withdrawal Confirmed'), ('withdrawal_failed', 'Withdrawal Failed'), ('completed', 'Completed'), ('failed', 'Failed'), ('webhook_received', 'Webhook Received'), ('webhook_processed', 'Webhook Processed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transferlimitsnapshot',
            name='corridor',
            field=models.ForeignKey(blank=True, help_text='Source → destination corridor used for this transfer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='limit_snapshots', to='routes.corridor'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['deposit_reference'], name='transfers_t_deposit_3050ae_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['withdrawal_reference'], name='transfers_t_withdra_3c5432_idx'),
        ),
    ]
