# Generated by Django 5.0.1 on 2025-12-30 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Corridor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iso_code", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "phone_prefix",
                    models.CharField(help_text="+237, +225, etc.", max_length=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorridorFundingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("mobile_money", "Mobile Money"),
                            ("card", "Card"),
                            ("bank", "Bank"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mobile_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mtn_cm", "MTN Cameroon"),
                            ("orange_cm", "Orange Money Cameroon"),
                            ("wave_sn", "Wave Senegal"),
                            ("mtn_ci", "MTN Côte d’Ivoire"),
                            ("orange_ci", "Orange Money Côte d’Ivoire"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "card_scheme",
                    models.CharField(
                        blank=True, help_text="visa, mastercard, etc.", max_length=20
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "corridor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_methods",
                        to="routes.corridor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorridorPayoutMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("mobile_money", "Mobile Money"),
                            ("card", "Card"),
                            ("bank", "Bank"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mobile_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mtn_cm", "MTN Cameroon"),
                            ("orange_cm", "Orange Money Cameroon"),
                            ("wave_sn", "Wave Senegal"),
                            ("mtn_ci", "MTN Côte d’Ivoire"),
                            ("orange_ci", "Orange Money Côte d’Ivoire"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "corridor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_methods",
                        to="routes.corridor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="corridor",
            name="destination_country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_corridors",
                to="routes.country",
            ),
        ),
        migrations.AddField(
            model_name="corridor",
            name="source_country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_corridors",
                to="routes.country",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="corridor",
            unique_together={("source_country", "destination_country")},
        ),
    ]
