# Generated by Django 5.0.1 on 2026-01-06 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0002_alter_corridorfundingmethod_card_scheme_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="corridorpayoutmethod",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="corridorpayoutmethod",
            name="corridor",
        ),
        migrations.AlterModelOptions(
            name="corridor",
            options={"ordering": ["source_country", "destination_country"]},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="corridor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="corridor",
            name="fixed_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Fixed fee in base currency",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="corridor",
            name="max_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=10000000,
                help_text="Maximum transfer amount",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="corridor",
            name="min_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                help_text="Minimum transfer amount",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="corridor",
            name="percentage_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentage fee (e.g., 1.50 for 1.5%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="corridor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="country",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name="corridor",
            table="routes_corridor",
        ),
        migrations.AlterModelTable(
            name="country",
            table="routes_country",
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_category",
                    models.CharField(
                        choices=[
                            ("funding", "Funding Method (How sender pays)"),
                            ("payout", "Payout Method (How receiver gets money)"),
                            ("both", "Both funding and payout"),
                        ],
                        default="both",
                        help_text="Whether this method can be used for funding, payout, or both",
                        max_length=20,
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("mobile_money", "Mobile Money"),
                            ("card", "Card"),
                            ("bank", "Bank"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mobile_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mtn_cm", "MTN Mobile Money (Cameroon)"),
                            ("orange_cm", "Orange Money (Cameroon)"),
                            ("mtn_ci", "MTN Mobile Money (Côte d'Ivoire)"),
                            ("orange_ci", "Orange Money (Côte d'Ivoire)"),
                            ("moov_ci", "Moov Money (Côte d'Ivoire)"),
                            ("wave_ci", "Wave (Côte d'Ivoire)"),
                            ("orange_sn", "Orange Money (Senegal)"),
                            ("free_sn", "Free Money (Senegal)"),
                            ("wave_sn", "Wave (Senegal)"),
                            ("orange_ml", "Orange Money (Mali)"),
                            ("moov_ml", "Moov Money (Mali)"),
                            ("orange_bf", "Orange Money (Burkina Faso)"),
                            ("moov_bf", "Moov Money (Burkina Faso)"),
                            ("togocom_tg", "Togocom Money (Togo)"),
                            ("moov_tg", "Moov Money (Togo)"),
                            ("mtn_bj", "MTN Mobile Money (Benin)"),
                            ("moov_bj", "Moov Money (Benin)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "card_scheme",
                    models.CharField(
                        blank=True, help_text="visa, mastercard, amex", max_length=20
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher = displayed first"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="routes.country",
                    ),
                ),
            ],
            options={
                "db_table": "routes_payment_method",
                "ordering": ["-priority", "method_type", "mobile_provider"],
                "unique_together": {
                    ("country", "method_type", "mobile_provider", "card_scheme")
                },
            },
        ),
        migrations.DeleteModel(
            name="CorridorFundingMethod",
        ),
        migrations.DeleteModel(
            name="CorridorPayoutMethod",
        ),
    ]
