# Generated by Django 5.0.1 on 2025-12-30 11:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KYCProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("nationality", models.CharField(max_length=100)),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state_province", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                (
                    "kyc_level",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("under_review", "Under Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KYC Profile",
                "verbose_name_plural": "KYC Profiles",
            },
        ),
        migrations.CreateModel(
            name="KYCDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("national_id", "National ID"),
                            ("passport", "Passport"),
                            ("drivers_license", "Driver's License"),
                            ("proof_of_address", "Proof of Address"),
                            ("bank_statement", "Bank Statement"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        upload_to="kyc_documents/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("document_number", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("under_review", "Under Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("file_size", models.BigIntegerField(help_text="Size in bytes")),
                (
                    "file_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kyc_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="kyc.kycprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "KYC Document",
                "verbose_name_plural": "KYC Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KYCVerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("resubmitted", "Resubmitted"),
                            ("document_added", "Document Added"),
                            ("document_verified", "Document Verified"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kyc_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_logs",
                        to="kyc.kycprofile",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kyc_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KYC Verification Log",
                "verbose_name_plural": "KYC Verification Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="kycprofile",
            index=models.Index(
                fields=["user", "verification_status"],
                name="kyc_kycprof_user_id_d5751f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kycprofile",
            index=models.Index(
                fields=["kyc_level"], name="kyc_kycprof_kyc_lev_31b96e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycdocument",
            index=models.Index(
                fields=["kyc_profile", "document_type"],
                name="kyc_kycdocu_kyc_pro_1f5dd1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kycdocument",
            index=models.Index(fields=["status"], name="kyc_kycdocu_status_91d83a_idx"),
        ),
    ]
