# Generated by Django 5.0.1 on 2025-12-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="kycdocument",
            name="kyc_kycdocu_kyc_pro_1f5dd1_idx",
        ),
        migrations.AddField(
            model_name="kycdocument",
            name="document_side",
            field=models.CharField(
                choices=[
                    ("front", "Front"),
                    ("back", "Back"),
                    ("single", "Single (No back required)"),
                ],
                default="single",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="kycdocument",
            name="file_hash",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="kycprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="kycprofile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="kycdocument",
            unique_together={("kyc_profile", "document_type", "document_side")},
        ),
        migrations.AddIndex(
            model_name="kycdocument",
            index=models.Index(
                fields=["kyc_profile", "document_type", "document_side"],
                name="kyc_kycdocu_kyc_pro_fb54c8_idx",
            ),
        ),
    ]
