# Generated by Django 5.0.1 on 2025-12-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0002_remove_kycdocument_kyc_kycdocu_kyc_pro_1f5dd1_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("national_id", "National ID"),
                    ("passport", "Passport"),
                    ("drivers_license", "Driver's License"),
                    ("proof_of_address", "Proof of Address"),
                    ("bank_statement", "Bank Statement"),
                    ("selfie", "Selfie"),
                ],
                max_length=50,
            ),
        ),
    ]
