# Generated by Django 5.0.1 on 2026-01-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0003_alter_kycdocument_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("under_review", "Under Review"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="kycprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("under_review", "Under Review"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
