# Generated by Django 5.0.1 on 2026-01-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0004_alter_kycdocument_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="kycprofile",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
