# Generated by Django 5.0.1 on 2026-01-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0005_alter_kycprofile_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycprofile",
            name="nationality",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
