# Generated by Django 5.0.1 on 2026-01-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0006_alter_kycprofile_nationality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("under_review", "Under Review"),
                ],
                default="not_submitted",
                max_length=20,
            ),
        ),
    ]
