# Generated by Django 5.0.1 on 2025-12-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdevice",
            name="device_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique device identifier from mobile app",
                max_length=255,
            ),
        ),
    ]
