# Generated by Django 5.0.1 on 2025-12-30 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_userdevice_device_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("reset", "Password Reset"),
                            ("change", "Password Change"),
                            ("forced", "Forced Change"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password History",
                "verbose_name_plural": "Password Histories",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["token", "expires_at"], name="authenticat_token_352abb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["user", "used_at"], name="authenticat_user_id_46a71f_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="passwordresettoken",
            table=None,
        ),
        migrations.AddField(
            model_name="passwordhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
