# Generated by Django 5.0.1 on 2025-12-30 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0003_passwordhistory_alter_passwordresettoken_token_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_kyc_sta_4052e1_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="kyc_level",
        ),
        migrations.RemoveField(
            model_name="user",
            name="kyc_status",
        ),
        migrations.RemoveField(
            model_name="user",
            name="kyc_verified_at",
        ),
    ]
