# Generated by Django 5.0.1 on 2026-01-05 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_remove_user_users_kyc_sta_4052e1_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="daily_limit",
        ),
        migrations.RemoveField(
            model_name="user",
            name="transaction_limit",
        ),
    ]
